stockhelper/stockapp/urls.py
from django.urls import path

from . import views

app_name = "stockapp"
urlpatterns = [
    path("", views.get_index, name="index"),
    path("screener", views.get_stocks, name="screener"),
    path("details/<ticker>", views.get_stock_details, name="detail"),
    path("flashcards", views.FlashCardsView.as_view(), name="flashcards"),
    path("portfolio", views.get_portfolio, name="portfolio"),
    path("session/balance", views.SessionBalanceView.as_view(), name="balance"),
    path("api/price/<ticker>", views.PriceView.as_view(), name="price")
]

stockhelper/stockhelper/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

from stockhelper import views

urlpatterns = [
    # Redirect the root path to the home page of stockapp
    path("", RedirectView.as_view(url=reverse_lazy("stockapp:index"), permanent=True)),
    # Redirect .well-known/change-password to the change password screen
    path(
        ".well-known/change-password",
        RedirectView.as_view(url=reverse_lazy("password_change"), permanent=True),
    ),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/create", views.create_account, name="create"),
    path("accounts/delete", views.delete_account, name="delete"),
    path("stockapp/", include("stockapp.urls")),
]

stockhelper/stockapp/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
import uuid


# The user (extends Django's existing User object)
class User(AbstractUser):
    # Start off with a default balance of $10,000
    balance = models.DecimalField(
        max_digits=7, decimal_places=2, default=10000)


# Information about each stock
class Stock(models.Model):
    # Each stock ticker is unique
    ticker = models.CharField(primary_key=True, max_length=10)
    name = models.CharField(max_length=100, default="")
    price = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    change = models.FloatField(default=0)

    def __str__(self):
        return f"{self.ticker} - {self.name}"


# The user's stock portfolio
class Portfolio(models.Model):
    # UUIDs are more secure than the default id
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # One user can own many stocks
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    # Many portfolios from different users can contain the same stock
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    shares = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.user}: {self.shares} {'share' if self.shares == 1 else 'shares'} of {self.stock}"


# Object representing the flashcards
class Card(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    word = models.CharField(max_length=50)
    definition = models.TextField()

    def __str__(self):
        return f"{self.word} - {self.definition}"

stockhelper/stockapp/forms.py
from django import forms


class ScreenerForm(forms.Form):
    # Constants
    COUNTRIES = [
        ("AI", "Anguilla"),
        ("AR", "Argentina"),
        ("AU", "Australia"),
        ("AT", "Austria"),
        ("AZ", "Azerbaijan"),
        ("BS", "Bahamas"),
        ("BD", "Bangladesh"),
        ("BB", "Barbados"),
        ("BE", "Belgium"),
        ("BM", "Bermuda"),
        ("BR", "Brazil"),
        ("BG", "Bulgaria"),
        ("KH", "Cambodia"),
        ("CA", "Canada"),
        ("KY", "Cayman Islands"),
        ("CL", "Chile"),
        ("CN", "China"),
        ("CO", "Colombia"),
        ("CK", "Cook Islands"),
        ("CR", "Costa Rica"),
        ("CI", "Côte d'Ivoire"),
        ("CW", "Curaçao"),
        ("CY", "Cyprus"),
        ("CZ", "Czech Republic"),
        ("DK", "Denmark"),
        ("DO", "Dominican Republic"),
        ("FK", "Falkland Islands"),
        ("FI", "Finland"),
        ("FO", "Faroe Islands"),
        ("FR", "France"),
        ("GA", "Gabon"),
        ("GE", "Georgia"),
        ("DE", "Germany"),
        ("GI", "Gibraltar"),
        ("GR", "Greece"),
        ("GG", "Guernsey"),
        ("HK", "Hong Kong"),
        ("HU", "Hungary"),
        ("IS", "Iceland"),
        ("IN", "India"),
        ("ID", "Indonesia"),
        ("IE", "Ireland"),
        ("IM", "Isle of Man"),
        ("IL", "Israel"),
        ("IT", "Italy"),
        ("JP", "Japan"),
        ("JE", "Jersey"),
        ("JO", "Jordan"),
        ("LI", "Liechtenstein"),
        ("LT", "Lithuania"),
        ("LU", "Luxembourg"),
        ("MO", "Macao"),
        ("MY", "Malaysia"),
        ("MT", "Malta"),
        ("MU", "Mauritius"),
        ("MX", "Mexico"),
        ("MC", "Monaco"),
        ("MN", "Mongolia"),
        ("MA", "Morocco"),
        ("NL", "Netherlands"),
        ("NZ", "New Zealand"),
        ("NG", "Nigeria"),
        ("NO", "Norway"),
        ("PA", "Panama"),
        ("PG", "Papua New Guinea"),
        ("PE", "Peru"),
        ("PH", "Philippines"),
        ("PL", "Poland"),
        ("PT", "Portugal"),
        ("PR", "Puerto Rico"),
        ("RU", "Russia"),
        ("SN", "Senegal"),
        ("SG", "Singapore"),
        ("SK", "Slovakia"),
        ("SB", "Solomon Islands"),
        ("ZA", "South Africa"),
        ("KR", "South Korea"),
        ("ES", "Spain"),
        ("SE", "Sweden"),
        ("CH", "Switzerland"),
        ("TW", "Taiwan"),
        ("TH", "Thailand"),
        ("TG", "Togo"),
        ("TR", "Turkey"),
        ("TC", "Turks and Caicos Islands"),
        ("UA", "Ukraine"),
        ("AE", "United Arab Emirates"),
        ("GB", "United Kingdom"),
        ("US", "United States"),
        ("UY", "Uruguay"),
        ("VN", "Vietnam"),
        ("VG", "Virgin Islands (U.K.)"),
        ("VI", "Virgin Islands (U.S.)"),
        ("ZM", "Zambia")
    ]

    RELATIONS = [
        # (A, B) will have the same value
        ("<",) * 2,
        (">",) * 2
    ]

    SECTORS = [
        ("Any",) * 2,  # if the user doesn't want to filter by sector
        ("Basic Materials",) * 2,
        ("Communication Services",) * 2,
        ("Conglomerates",) * 2,
        ("Consumer Cyclical",) * 2,
        ("Consumer Defensive",) * 2,
        ("Energy",) * 2,
        ("Financial",) * 2,
        ("Financial Services",) * 2,
        ("Healthcare",) * 2,
        ("Industrial Goods",) * 2,
        ("Industrials",) * 2,
        ("Real Estate",) * 2,
        ("Services",) * 2,
        ("Technology",) * 2,
        ("Utilities",) * 2
    ]

    EXCHANGES = [
        ("Any",) * 2,  # if the user doesn't want to filter by exchange
        ("nyse", "NYSE"),
        ("nasdaq", "NASDAQ"),
        ("amex", "AMEX"),
        ("euronext", "EURONEXT"),
        ("tsx", "TSX"),
        ("etf", "ETF"),
        ("mutual_fund", "Mutual Fund")
    ]

    # Fields (widgets specify the classes to put in)
    country = forms.ChoiceField(label="Country", choices=COUNTRIES, widget=forms.Select(
        attrs={"class": "country-select col form-select"}
    ))
    # Put the two fields on the same lines
    price_relation = forms.ChoiceField(choices=RELATIONS, widget=forms.Select(
        attrs={"class": "price-relation-select col form-select me-3"}
    ))
    price_value = forms.DecimalField(min_value=0, decimal_places=2, widget=forms.NumberInput(
        attrs={"inputmode": "decimal",
               "class": "price-num-input col form-control"}
    ))
    sector = forms.ChoiceField(label="Sector", choices=SECTORS, widget=forms.Select(
        attrs={"class": "sector-select col form-select"}
    ))

    exchange = forms.ChoiceField(label="Exchange", choices=EXCHANGES, widget=forms.Select(
        attrs={"class": "exchange-select col form-select"}
    ))

stockhelper/stockapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from . import api
from .forms import ScreenerForm
from .models import Card, Portfolio, Stock
from decimal import Decimal
from http import HTTPStatus
import json


# Home view
def get_index(request):
    # Aggregate all the terms needed for each page
    terms = {
        "equity": Card.objects.get(word="Equity")
    }

    return render(request, "stockapp/index.html", {
        "terms": terms,
        "user": request.user
    })


# Screener view
def get_stocks(request):
    if request.method == "POST":
        # Keep the form as is after submitting
        form = ScreenerForm(request.POST)

        # Check if the form is bound to data and doesn't have any errors
        if form.is_valid():
            # Query the dataset
            stock_data = api.get_stocks(form.cleaned_data)
            print(f"{stock_data=}")

            # If stock_data isn't a list (due to an API error), treat it like there are no results
            if isinstance(stock_data, list):
                request.session["results"] = stock_data

            # Return an HttpResponseRedirect to prevent the data from being posted twice
            return HttpResponseRedirect(reverse("stockapp:screener"))

    # Show an empty form when entering the screener page
    form = ScreenerForm()
    # Display the results after a POST request
    # results will be None if there aren't any results
    results = request.session.get("results")
    # don't throw an error if the key isn't present
    request.session.pop("results", None)

    terms = {
        "beta": Card.objects.get(word="Beta"),
        "dividendYield": Card.objects.get(word="Dividend Yield"),
        "etf": Card.objects.get(word="ETF"),
        "index": Card.objects.get(word="Index"),
        "indexFund": Card.objects.get(word="Index Fund"),
        "marketCap": Card.objects.get(word="Market Cap"),
        "marketExchange": Card.objects.get(word="Market Exchange"),
        "mutualFund": Card.objects.get(word="Mutual Fund"),
        "sharePrice": Card.objects.get(word="Share Price"),
        "volume": Card.objects.get(word="Volume")
    }
    sorted_symbols = list(sorted(api.FREE_TIER_SYMBOLS.items(), key=lambda symbol: symbol[0]))

    return render(request, "stockapp/screener.html", {
        "form": form,
        "results": results,
        "terms": terms,
        "freeTierSymbols": sorted_symbols
    })


# Details view
# Users are required to log in if the view requires access to their balance (cookie lasts 2 weeks)
@login_required
def get_stock_details(request, ticker):
    if request.method == "POST":
        # Make changes to the user's shares
        # Since this isn't form data, the request body needs to be decoded
        stock_info = json.loads(request.body)
        symbol = stock_info.get("ticker")
        name = stock_info.get("name")
        is_buying = stock_info.get("isBuying")
        shares = stock_info.get("shares")
        price = stock_info.get("price")
        change = stock_info.get("change")

        # Read: show all the stocks the user bought (done in the portfolio view)
        try:
            # Check if the user already owns this stock
            existing_stock = Stock.objects.get(ticker=symbol)
            existing_portfolio = Portfolio.objects.get(
                user=request.user, stock=existing_stock)

            # Update: buy or sell an existing stock --> update the number of shares
            if is_buying:
                existing_portfolio.shares += shares
                existing_portfolio.save()
            elif shares == existing_portfolio.shares:
                # Delete: sell all the shares of a stock --> delete it from the portfolio
                existing_portfolio.delete()
            elif shares > existing_portfolio.shares:
                # Error: the user sold too many shares
                return JsonResponse(
                    {"status": "failure", "maxShares": existing_portfolio.shares},
                    status=HTTPStatus.BAD_REQUEST  # status code 400 = client-side error
                )
            else:
                existing_portfolio.shares -= shares
                existing_portfolio.save()
        except Stock.DoesNotExist:
            # If Stock.get() throws an error
            if is_buying:
                # Create: a new stock is bought --> create the Stock and Portfolio objects
                new_stock = Stock.objects.create(
                    ticker=symbol, name=name, price=price, change=change)
                Portfolio.objects.create(
                    user=request.user, stock=new_stock, shares=shares)
            else:
                # Error: the user can't sell any shares
                return JsonResponse({"status": "failure", "maxShares": 0},
                                    status=HTTPStatus.BAD_REQUEST)
        except Portfolio.DoesNotExist:
            # If Portfolio.get() throws an error
            if is_buying:
                # Create: a new stock is bought --> create the portfolio and add the existing stock
                Portfolio.objects.create(
                    user=request.user, stock=existing_stock, shares=shares)
            else:
                # Error: the user can't sell any shares
                return JsonResponse({"status": "failure", "maxShares": 0},
                                    status=HTTPStatus.BAD_REQUEST)

        # Update the user's balance
        if is_buying:
            request.user.balance -= Decimal(shares * price)
        else:
            request.user.balance += Decimal(shares * price)

        request.user.save()
        return JsonResponse({"status": "success"})

    # Fetch details about a company and display it to the user
    raw_profile = api.get_company_profile(ticker)  # returns a list of dicts
    # returns a dict with symbol and historical list
    raw_history = api.get_stock_history(ticker)
    print(f"{raw_profile=}")
    print(f"{raw_history=}")

    terms = {
        "beta": Card.objects.get(word="Beta"),
        "broker": Card.objects.get(word="Broker"),
        "dividendYield": Card.objects.get(word="Dividend Yield"),
        "marketCap": Card.objects.get(word="Market Cap"),
        "marketExchange": Card.objects.get(word="Market Exchange"),
        "marketOrder": Card.objects.get(word="Market Order"),
        "risk": Card.objects.get(word="Risk"),
        "trader": Card.objects.get(word="Trader"),
        "volatility": Card.objects.get(word="Volatility"),
        "volume": Card.objects.get(word="Volume")
    }
    status = 200

    # profile should be an array with one element, display an error if that's not the case
    if not raw_profile:
        profile = None
        status = 400
    elif isinstance(raw_profile, list) and len(raw_profile) >= 1:
        profile = raw_profile[0]
    else:
        profile = raw_profile
        status = 400

    # history should be an array of dicts, display an error if that's not the case
    if isinstance(raw_history, list):
        history = raw_history
    elif isinstance(raw_history, dict) and "Error Message" in raw_history:
        history = raw_history
        status = 400
    else:
        history = ticker
        status = 400

    return render(request, "stockapp/detail.html", {
        "profile": profile,
        "history": history,
        "balance": request.user.balance,
        "terms": terms
    }, status=status)


# Flashcards view
class FlashCardsView(generic.ListView):
    model = Card
    template_name = "stockapp/flashcards.html"
    context_object_name = "cards"

    def get_queryset(self):
        """
        Sort the cards alphabetically
        """
        return Card.objects.order_by("word")


# Portfolio view
@login_required
def get_portfolio(request):
    terms = {
        "portfolio": Card.objects.get(word="Portfolio"),
        "roi": Card.objects.get(word="ROI"),
        "sharePrice": Card.objects.get(word="Share Price")
    }

    # Join the ticker, name, and shares into one QuerySet
    # stock__ticker = stock.ticker
    portfolios = Portfolio.objects.filter(user=request.user).values(
        "stock__ticker", "stock__name", "shares")

    return render(request, "stockapp/portfolio.html", {
        "balance": request.user.balance,
        "portfolios": portfolios,
        "terms": terms
    })


# A view only meant to retrieve the balance through a GET request
# https://stackoverflow.com/a/36073883
class SessionBalanceView(LoginRequiredMixin, generic.base.TemplateView):
    def get(self, request):
        return HttpResponse(request.user.balance)


class PriceView(LoginRequiredMixin, generic.base.TemplateView):
    def get(self, request, ticker):
        # Get the price, change, and shares of the given ticker
        # Tickers are stored in all caps, but the request should be case insensitive
        upper_ticker = ticker.upper()

        try:
            # SELECT Stock.price, Stock.change, Porfolio.shares
            # FROM Stock JOIN Portfolio ON Stock.ticker = Porfolio.stock
            # WHERE Stock.ticker = <ticker> AND Porfolio.user =
            # (SELECT username FROM User WHERE username = <request.user>)
            portfolio = Portfolio.objects.get(
                user=request.user, stock=upper_ticker)
            stock = portfolio.stock
            raw_profile = api.get_company_profile(upper_ticker)
            print(f"{raw_profile=}")

            # profile should be an array with one element, display an error if that's not the case
            if not raw_profile:
                return JsonResponse({
                    "error": f"No stock {upper_ticker} found"
                }, status=HTTPStatus.BAD_REQUEST)

stockhelper/stockapp/templates/stockapp/flashcards.html
{% extends "stockapp/index.html" %}
{% load static %}

{% block title %}Flashcards{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'stockapp/css/flashcards.css' %}">
{% endblock %}

{% block js %}
<script src="{% static 'stockapp/js/flashcards.js' %}"></script>
{% endblock %}

{% block content %}
<h1 class="description text-center">Click on a card to learn each term.</h1>
{% for card in cards.all %}
<div class="flashcard card shadow bg-light" tabindex="0" aria-label="{{ card.word }}">
    <div class="card-body">
        <h2 class="word card-title fs-4">{{ card.word }}</h2>
        <p class="definition card-text fade-out hidden" hidden>{{ card.definition }}</p>
    </div>
</div>
{% endfor %}
{% endblock %}

stockhelper/stockapp/templates/stockapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A stock trading app designed for beginners">
    <!-- Allow the title to be overriden based on the current page -->
    <title>{% block title %}Home{% endblock %} | How to Stock</title>
    <link rel="icon" type="image/png" href="{% static 'stockapp/icon/favicon.ico' %}">
    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'stockapp/css/home.css' %}">
    <!-- Page-specific CSS -->
    {% block css %}{% endblock %}
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'stockapp:index' %}">How to Stock</a>
            <!-- Hamburger icon to expand and collapse the navbar -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="link-home nav-link active" aria-current="page"
                            href="{% url 'stockapp:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="link-screener nav-link" href="{% url 'stockapp:screener' %}">Screener</a>
                    </li>
                    <li class="nav-item">
                        <a class="link-flashcards nav-link" href="{% url 'stockapp:flashcards' %}">Flashcards</a>
                    </li>
                    <li class="nav-item">
                        <a class="link-portfolio nav-link" href="{% url 'stockapp:portfolio' %}">Portfolio</a>
                    </li>
                </ul>
                <!-- If the user is logged in, show their username, else show the Login button -->
                {% if user.is_authenticated %}
                <span class="nav-item dropdown">
                    <a class="dropdown-user nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <!-- Don't position the dropdown menu beyond the screen for large displays -->
                    <ul class="dropdown-list dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
                        <li>
                            <form method="post" action="{% url 'logout' %}">
                                {% csrf_token %}
                                <button type="submit" class="dropdown-item">Logout</button>
                            </form>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item link-danger" href="{% url 'delete' %}">Delete Account</a>
                        </li>
                    </ul>
                </span>
                {% else %}
                <span class="nav-item">
                    <a class="link-login nav-link" href="{% url 'login' %}">Login</a>
                </span>
                {% endif %}
            </div>
        </div>
    </nav>
    <main class="main-content">
        <!-- Main content to be overriden with each page -->
        {% block content %}
        <h1 class="home-title mt-3 mx-3">Welcome to How to Stock!</h1>
        <p class="home-subtitle mb-4 mx-3 fs-5">
            You start off with a balance of $10,000. Your goal is to invest in enough
            <a tabindex="0" href="javascript:" class="equity help fw-bold" data-bs-toggle="popover"
                data-bs-trigger="focus" data-bs-container="body" data-bs-placement="top" title="{{ terms.equity.word }}"
                data-bs-content="{{ terms.equity.definition }}"> equity </a>
            to gain a profit. ▲
        </p>
        <p class="home-subtitle mb-4 mx-3 fs-5">
            As you explore this app, you'll learn more about various financial terms and get first-hand experience at
            trading in the stock market. Not sure what each term means? Click on the dotted words to see their
            definition.
        </p>
        <p class="home-subtitle mb-4 mx-3 fs-5">
            Click on one the links above to get started!
        </p>
        <ul class="home-nav-list list-group list-group-flush mx-3">
            <li class="list-group-item">
                <strong>Home</strong> - this page!
            </li>
            <li class="list-group-item">
                <strong>Screener</strong> - select different stocks by filters
            </li>
            <li class="list-group-item">
                <strong>Flashcards</strong> - learn more about various financial terms
            </li>
            <li class="list-group-item">
                <strong>Portfolio</strong> - view details about your investments
            </li>
        </ul>
        {% endblock %}
    </main>
    <footer class="credit bg-dark">
        <a href="https://site.financialmodelingprep.com/developer/docs" class="text-info" target="_blank"
            rel="noopener noreferrer">Data provided by Financial Modeling Prep</a>
    </footer>
    <!-- JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script src="{% static 'stockapp/js/home.js' %}"></script>
    <!-- Page-specific JS -->
    {% block js %}{% endblock %}
</body>

</html>

stockhelper/stockapp/templates/stockapp/portfolio.html
{% extends "stockapp/index.html" %}
{% load static %}
{% load custom_tags %}

{% block title %}Portfolio{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'stockapp/css/portfolio.css' %}">
{% endblock %}

{% block js %}
<script src="{% static 'stockapp/js/portfolio.js' %}"></script>
{% endblock %}

{% block content %}
<div class="roi-alert alert alert-info alert-dismissible fade show" role="alert">
    <p class="portfolio-info">
        This is your stock
        <a tabindex="0" href="javascript:" class="portfolio help" data-bs-toggle="popover" data-bs-trigger="focus"
            data-bs-container="body" data-bs-placement="bottom" title="{{ terms.portfolio.word }}"
            data-bs-content="{{ terms.portfolio.definition }}"> portfolio</a>
        . Your balance is the amount of cash you have at hand and your net worth is equal to your current balance + the
        value of each stock (# of shares * share price). Your goal is to gain a net positive
        <a tabindex="0" href="javascript:" class="roi help" data-bs-toggle="popover" data-bs-trigger="focus"
            data-bs-container="body" data-bs-placement="bottom" title="{{ terms.roi.word }}"
            data-bs-content="{{ terms.roi.definition }}"> ROI
        </a>
        by investing wisely in the right stocks.
    </p>
    <p class="portfolio-status"></p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<div class="money-container mx-3">
    <div class="balance-container">
        <h1>Balance</h1>
        <h2 class="balance">${{ balance|money_commas }}</h2>
    </div>
    <div class="net-worth-container">
        <h1>Net Worth</h1>
        <!-- Show a spinner while the net worth is being calculated -->
        <div class="net-worth-spinner spinner-border text-primary" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
        <h2 class="net-worth"></h2>
    </div>
</div>
<hr>
<h1>Stocks</h1>
{% if not portfolios %}
<p class="text-muted">Nothing yet...start investing!</p>
{% else %}
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Ticker</th>
                <th>Company Name</th>
                <th>Shares</th>
                <th>
                    <a tabindex="0" href="javascript:" class="share-price help" data-bs-toggle="popover"
                        data-bs-trigger="focus" data-bs-container="body" data-bs-placement="top"
                        title="{{ terms.sharePrice.word }}" data-bs-content="{{ terms.sharePrice.definition }}">Share
                        Price</a>
                </th>
                <th>Price Change</th>
            </tr>
        </thead>
        <tbody>
            {% for portfolio in portfolios %}
            <tr class="table-row" role="link" tabindex="0">
                <td class="stock-ticker">{{ portfolio.stock__ticker }}</td>
                <td class="stock-name">{{ portfolio.stock__name }}</td>
                <td class="stock-shares">{{ portfolio.shares }}</td>
                <td class="stock-price">
                    <div class="price-spinner spinner-border text-primary" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                </td>
                <td class="stock-change">
                    <div class="change-spinner spinner-border text-primary" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}